#!/bin/bash

# Add branch as repo, to allow chained builds
echo "deb [trusted=yes] http://jenkins.trisquel.info/jenkins-repos/$BUILDBRANCH ./" >> /etc/apt/sources.list

# Some packages are built using packages from $BUILDDIST-updates
if [ x"$BUILDPACKAGE" = xtoxcore ] || $([ x"$BUILDPACKAGE" = xfirefox ] && [ x"$BUILDDIST" = xtoutatis ])
        then
                echo "deb http://es.archive.trisquel.info/trisquel/ $BUILDDIST-updates main" >> /etc/apt/sources.list
        fi

apt-get update
