#!/bin/bash -x

echo "Trisquel build environment setup"
env
case "$BUILDDIST" in
        "belenos")
          export UBURELEASE=trusty
           export REVISION=7.0
           ;;
        "toutatis")
           export UBURELEASE=precise
           REVISION=6.0.1
          ;;
        "taranis")
           export UBURELEASE=lucid
           REVISION=4.0
           ;;
esac

# sources are addedd in the slave load script
#if ! `grep -q 'archive.ubuntu.com' /etc/apt/sources.list  `
#  then
#    echo "deb-src http://archive.ubuntu.com/ubuntu/ trusty main universe multiverse" >> /etc/apt/sources.list
#  fi

cat << EOF > /etc/apt/apt.conf.d/90recommends
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF

#Avoid asking for modified config files
cat << EOF > /etc/apt/apt.conf.d/40localconfig
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
}
EOF

#echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/02apt-speedup


# pkgbinarymangler
mkdir -p /etc/pkgbinarymangler/
cat << EOF > /etc/pkgbinarymangler/striptranslations.conf
enable: true
components: main
invalid_currentlybuilding: ignore
posuffix: translations
oem_blacklist: partner
EOF

cat << EOF > /etc/pkgbinarymangler/sanitychecks.conf
enable: true
EOF

cat << EOF > /etc/pkgbinarymangler/maintainermangler.conf
enable: false
invalid_currentlybuilding: ignore
EOF

cat << EOF > /etc/pkgbinarymangler/maintainermangler.overrides
default: Trisquel GNU/Linux developers <trisquel-devel@listas.trisquel.info>
ignore_domains: trisquel.info sognus.com listas.trisquel.info gnu.org fsf.org
ignore_emails: ruben@trisquel.info
EOF

cat << EOF > /etc/pkgbinarymangler/striptranslations.blacklist
iso-codes
dpkg
language-pack.*
debconf-i18n
apt
libapt-pkg.*
libapt-inst.*
xkb-data-i18n
ldm
EOF

cat << EOF > /etc/pkgbinarymangler/striptfiles.conf
enable: true
EOF
# end pkgbinarymangler

source /etc/lsb-release
cat << EOF >/etc/apt/sources.list
#Trisquel binary packages
deb http://archive.trisquel.info/trisquel/ $BUILDDIST  main
deb http://archive.trisquel.info/trisquel/ $BUILDDIST-security  main

#Ubuntu source packages
deb-src http://archive.ubuntu.com/ubuntu $UBURELEASE main universe
deb-src http://archive.ubuntu.com/ubuntu $UBURELEASE-updates main universe
deb-src http://archive.ubuntu.com/ubuntu $UBURELEASE-security main universe

EOF

echo devel.trisquel.info > /etc/hostname

apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 40976EAF437D05B5
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32

echo $BUILDDIST-$BUILDARCH > /etc/debian_chroot

# Fake uname and arch outputs
if [ $BUILDARCH = "i386" ]; then
  for BIN in /bin/uname /usr/bin/arch; do
    [ -f $BIN.orig ] || mv $BIN $BIN.orig
cat << EOF > $BIN
#!/bin/bash
$BIN.orig "\$@" | sed s/x86_64/i686/g
EOF
    chmod 755 $BIN
  done
fi

